#!/bin/bash
set -euo pipefail

# Claude Code Devcontainer CLI Helper
# Provides the `devc` command for managing devcontainers
# Uses Nix (dockerTools) for image builds and docker-compose for runtime

# Resolve symlinks to get actual script location
SOURCE="${BASH_SOURCE[0]}"
while [[ -L "$SOURCE" ]]; do
  DIR="$(cd "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$(cd "$(dirname "$SOURCE")" && pwd)"
SCRIPT_NAME="$(basename "$0")"

COMPOSE_SERVICE="shell"
IMAGE_NAME="claude-sandbox"
WRAPPER_DIR="$HOME/.cache/devc/wrappers"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_usage() {
  cat <<EOF
Usage: devc <command> [options]

Commands:
    .                   Install template to current directory and start
    up [--flake <ref>]  Build image and start the container
    rebuild [--flake <ref>]  Rebuild image and recreate container
    down                Stop the container
    shell               Open a shell in the running container
    wrapper [name]      Show generated wrapper flake(s)
    self-install        Install 'devc' command to ~/.local/bin
    update              Update devc to the latest version
    template [dir]      Copy compose template to directory (default: current)
    exec <cmd>          Execute a command in the running container
    upgrade             Upgrade Claude Code to latest version
    mount <host> <cont> Add a mount to the container (recreates container)
    mounts              Show current container mounts
    cp <cont> <host>    Copy files/directories from container to host
    firewall <on|off|status>  Manage container network firewall
    help                Show this help message

Flake flags (for up/rebuild):
    --flake <ref>       Project flake to include (path or URI)
    --shell <attr>      devShell attribute (default: devShells.x86_64-linux.default)

Examples:
    devc up                                 # Base container (no project deps)
    devc up --flake ~/code/xous-core        # Include project's devShell
    devc up --flake github:owner/repo       # Remote flake
    devc up --flake ./my-project --shell devShells.x86_64-linux.cross
    devc rebuild --flake ~/code/xous-core   # Rebuild with project deps
    devc wrapper                            # List generated wrappers
    devc wrapper xous-core                  # Show wrapper flake.nix
    devc shell                              # Open interactive shell
    devc exec ls -la                        # Run command in container
    devc firewall on                        # Enable default firewall rules
    devc firewall off                       # Disable firewall
EOF
}

log_info() {
  echo -e "${BLUE}[devc]${NC} $1"
}

log_success() {
  echo -e "${GREEN}[devc]${NC} $1"
}

log_warn() {
  echo -e "${YELLOW}[devc]${NC} $1"
}

log_error() {
  echo -e "${RED}[devc]${NC} $1" >&2
}

check_deps() {
  local missing=()
  command -v nix &>/dev/null || missing+=("nix (https://nixos.org/download/)")
  command -v docker &>/dev/null || missing+=("docker")
  if [[ ${#missing[@]} -gt 0 ]]; then
    log_error "Missing required tools:"
    for dep in "${missing[@]}"; do
      log_error "  - $dep"
    done
    exit 1
  fi
}

get_workspace_folder() {
  echo "${1:-$(pwd)}"
}

build_image() {
  local flake_ref="${1:-$SCRIPT_DIR#container}"
  local flake_dir="${flake_ref%%#*}"
  local result_link="$flake_dir/result"

  log_info "Building container image..."
  log_info "  nix build $flake_ref -L -o $result_link"
  nix build "$flake_ref" -L -o "$result_link"
  log_info "  docker load < $result_link"
  docker load < "$result_link"
  log_success "Image built: $IMAGE_NAME"
}

# Generate a wrapper flake that wires a project's devShell into mkDevContainer.
# The wrapper is a plain flake.nix you can read and edit.
generate_wrapper() {
  local project_flake="$1"
  local shell_attr="${2:-devShells.x86_64-linux.default}"

  # Resolve local paths to absolute
  if [[ -d "$project_flake" ]]; then
    project_flake="$(cd "$project_flake" && pwd)"
  fi

  # Derive a stable wrapper name from the flake ref
  local wrapper_name
  wrapper_name="$(basename "${project_flake%/}")"
  wrapper_name="${wrapper_name//[:\/]/-}"
  local wrapper_path="$WRAPPER_DIR/$wrapper_name"

  mkdir -p "$wrapper_path"

  # Determine the flake URL for the project input
  local project_url
  if [[ -d "$project_flake" ]]; then
    project_url="path:$project_flake"
  else
    project_url="$project_flake"
  fi

  cat > "$wrapper_path/flake.nix" << FLAKE_EOF
# Generated by devc — feel free to inspect or edit
#
# Wires a project devShell into the claude-code-devcontainer base image.
# Rebuild with: nix build $wrapper_path#container -L
{
  inputs = {
    devcontainer.url = "path:$SCRIPT_DIR";
    project.url = "$project_url";
  };

  outputs = { devcontainer, project, ... }: {
    packages.x86_64-linux.container =
      devcontainer.lib.x86_64-linux.mkDevContainer {
        projectShell = project.$shell_attr;
      };
  };
}
FLAKE_EOF

  log_info "Wrapper flake: $wrapper_path/flake.nix"
  log_info "  project:  $project_url"
  log_info "  shell:    $shell_attr"

  echo "$wrapper_path"
}

update_compose_mounts() {
  local compose_file="$1"
  local host_path="$2"
  local container_path="$3"
  local readonly="${4:-false}"
  local raw_entry="${5:-}"

  local mount_entry
  if [[ -n "$raw_entry" ]]; then
    mount_entry="$raw_entry"
  else
    mount_entry="$host_path:$container_path"
    [[ "$readonly" == "true" ]] && mount_entry="${mount_entry}:ro"
  fi

  if command -v yq &>/dev/null; then
    yq -i ".services.${COMPOSE_SERVICE}.volumes += [\"${mount_entry}\"]" "$compose_file"
  else
    log_warn "yq not found; appending mount manually"
    sed -i "/^    volumes:/a\\      - ${mount_entry}" "$compose_file"
  fi
}

extract_custom_volumes() {
  local compose_file="$1"
  [[ -f "$compose_file" ]] || return

  # Default volumes that ship with the template
  local defaults=(
    'claude-code-bashhistory:'
    'claude-code-config:'
    ':/workspace:'
  )

  local volumes_section=false
  local in_service_volumes=false
  local custom=()

  while IFS= read -r line; do
    # Detect the volumes key under the service
    if [[ "$line" =~ ^[[:space:]]+volumes: ]]; then
      in_service_volumes=true
      continue
    fi
    if $in_service_volumes; then
      # Volume entries are list items starting with "- "
      if [[ "$line" =~ ^[[:space:]]+-[[:space:]](.+) ]]; then
        local entry="${BASH_REMATCH[1]}"
        local is_default=false
        for pat in "${defaults[@]}"; do
          if [[ "$entry" == *"$pat"* ]]; then
            is_default=true
            break
          fi
        done
        $is_default || custom+=("$entry")
      elif [[ "$line" =~ ^[[:space:]]*$ ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
        # Skip blank lines and comments within volumes block
        continue
      else
        # Non-list-item line ends the volumes block
        in_service_volumes=false
      fi
    fi
  done < "$compose_file"

  printf '%s\n' "${custom[@]}"
}

merge_custom_volumes() {
  local compose_file="$1"
  shift
  local volumes=("$@")

  [[ ${#volumes[@]} -eq 0 ]] && return

  for entry in "${volumes[@]}"; do
    update_compose_mounts "$compose_file" "" "" "" "$entry"
  done
}

cmd_template() {
  local target_dir="${1:-.}"
  target_dir="$(cd "$target_dir" 2>/dev/null && pwd)" || {
    log_error "Directory does not exist: $1"
    exit 1
  }

  # Preserve custom volumes from existing compose file before overwriting
  local custom_volumes=()
  if [[ -f "$target_dir/docker-compose.yml" ]]; then
    while IFS= read -r vol; do
      [[ -n "$vol" ]] && custom_volumes+=("$vol")
    done < <(extract_custom_volumes "$target_dir/docker-compose.yml")
  fi

  if [[ -f "$target_dir/docker-compose.yml" ]]; then
    log_warn "docker-compose.yml already exists at $target_dir"
    read -p "Overwrite? [y/N] " -n 1 -r
    echo
    [[ $REPLY =~ ^[Yy]$ ]] || { log_info "Aborted."; exit 0; }
  fi

  cp "$SCRIPT_DIR/docker-compose.yml" "$target_dir/"
  cp -r "$SCRIPT_DIR/config" "$target_dir/"

  # Re-add any custom volumes that were in the previous compose file
  if [[ ${#custom_volumes[@]} -gt 0 ]]; then
    log_info "Preserving ${#custom_volumes[@]} custom volume(s)..."
    merge_custom_volumes "$target_dir/docker-compose.yml" "${custom_volumes[@]}"
  fi

  log_success "Template installed to $target_dir"
  log_info "Files: docker-compose.yml, config/"
}

# Parse --flake and --shell flags, returning via global vars
parse_flake_args() {
  FLAKE_REF=""
  SHELL_ATTR="devShells.x86_64-linux.default"
  POSITIONAL=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
    --flake)
      FLAKE_REF="${2:?--flake requires a flake reference}"
      shift 2
      ;;
    --flake=*)
      FLAKE_REF="${1#--flake=}"
      shift
      ;;
    --shell)
      SHELL_ATTR="${2:?--shell requires a devShell attribute}"
      shift 2
      ;;
    --shell=*)
      SHELL_ATTR="${1#--shell=}"
      shift
      ;;
    *)
      POSITIONAL+=("$1")
      shift
      ;;
    esac
  done
}

cmd_up() {
  parse_flake_args "$@"
  set -- "${POSITIONAL[@]}"

  local workspace_folder
  workspace_folder="$(get_workspace_folder "${1:-}")"

  check_deps

  log_info "Starting devcontainer in $workspace_folder..."

  if [[ -n "$FLAKE_REF" ]]; then
    local wrapper_path
    wrapper_path="$(generate_wrapper "$FLAKE_REF" "$SHELL_ATTR")"
    build_image "$wrapper_path#container"
  else
    build_image
  fi

  (cd "$workspace_folder" && docker compose up -d)

  log_success "Devcontainer started"
  log_info "Run 'devc shell' to open a shell"
}

cmd_rebuild() {
  parse_flake_args "$@"
  set -- "${POSITIONAL[@]}"

  local workspace_folder
  workspace_folder="$(get_workspace_folder "${1:-}")"

  check_deps

  log_info "Rebuilding devcontainer in $workspace_folder..."

  if [[ -n "$FLAKE_REF" ]]; then
    local wrapper_path
    wrapper_path="$(generate_wrapper "$FLAKE_REF" "$SHELL_ATTR")"
    build_image "$wrapper_path#container"
  else
    build_image
  fi

  (cd "$workspace_folder" && docker compose up -d --force-recreate)

  log_success "Devcontainer rebuilt"
}

cmd_down() {
  local workspace_folder
  workspace_folder="$(get_workspace_folder "${1:-}")"

  log_info "Stopping devcontainer..."
  (cd "$workspace_folder" && docker compose down)
  log_success "Devcontainer stopped"
}

cmd_shell() {
  local workspace_folder
  workspace_folder="$(get_workspace_folder)"

  (cd "$workspace_folder" && docker compose exec "$COMPOSE_SERVICE" zsh)
}

cmd_exec() {
  local workspace_folder
  workspace_folder="$(get_workspace_folder)"

  (cd "$workspace_folder" && docker compose exec "$COMPOSE_SERVICE" "$@")
}

cmd_upgrade() {
  local workspace_folder
  workspace_folder="$(get_workspace_folder)"

  log_info "Upgrading Claude Code..."
  (cd "$workspace_folder" && docker compose exec "$COMPOSE_SERVICE" claude update)
  log_success "Claude Code upgraded"
}

cmd_mount() {
  local host_path="${1:-}"
  local container_path="${2:-}"
  local readonly="false"

  if [[ -z "$host_path" ]] || [[ -z "$container_path" ]]; then
    log_error "Usage: devc mount <host_path> <container_path> [--readonly]"
    exit 1
  fi

  [[ "${3:-}" == "--readonly" ]] && readonly="true"

  host_path="$(cd "$host_path" 2>/dev/null && pwd)" || {
    log_error "Host path does not exist: $1"
    exit 1
  }

  local workspace_folder
  workspace_folder="$(get_workspace_folder)"
  local compose_file="$workspace_folder/docker-compose.yml"

  if [[ ! -f "$compose_file" ]]; then
    log_error "No docker-compose.yml found. Run 'devc template' first."
    exit 1
  fi

  check_deps

  log_info "Adding mount: $host_path → $container_path"
  update_compose_mounts "$compose_file" "$host_path" "$container_path" "$readonly"

  log_info "Recreating container with new mount..."
  (cd "$workspace_folder" && docker compose up -d --force-recreate)

  log_success "Mount added: $host_path → $container_path"
}

cmd_mounts() {
  local workspace_folder
  workspace_folder="$(get_workspace_folder)"

  local container
  container="$(cd "$workspace_folder" && docker compose ps -q "$COMPOSE_SERVICE" 2>/dev/null)"

  if [[ -z "$container" ]]; then
    log_error "Container is not running"
    exit 1
  fi

  docker inspect "$container" --format '{{range .Mounts}}{{.Type}}	{{.Source}} -> {{.Destination}}	{{if .RW}}rw{{else}}ro{{end}}{{println}}{{end}}'
}

cmd_cp() {
  local container_path="${1:-}"
  local host_path="${2:-}"

  if [[ -z "$container_path" ]] || [[ -z "$host_path" ]]; then
    log_error "Usage: devc cp <container_path> <host_path>"
    exit 1
  fi

  local workspace_folder
  workspace_folder="$(get_workspace_folder)"

  log_info "Copying $container_path → $host_path"
  (cd "$workspace_folder" && docker compose cp "$COMPOSE_SERVICE:$container_path" "$host_path")
  log_success "Copied $container_path → $host_path"
}

cmd_firewall() {
  local action="${1:-}"
  local workspace_folder
  workspace_folder="$(get_workspace_folder)"

  case "$action" in
  on)
    local config="${2:-$SCRIPT_DIR/config/firewall-defaults.conf}"
    if [[ ! -f "$config" ]]; then
      log_error "Config file not found: $config"
      exit 1
    fi

    log_info "Applying firewall rules from $config..."

    # Build iptables commands from config
    local cmds="iptables -F OUTPUT"
    while IFS= read -r line || [[ -n "$line" ]]; do
      line="${line%%#*}"        # strip comments
      line="${line// /}"        # strip whitespace
      [[ -z "$line" ]] && continue
      cmds="$cmds && iptables -A OUTPUT -d $line -j ACCEPT"
    done < "$config"
    cmds="$cmds && iptables -A OUTPUT -o lo -j ACCEPT"
    cmds="$cmds && iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT"
    cmds="$cmds && iptables -A OUTPUT -j DROP"

    (cd "$workspace_folder" && docker compose exec --user root "$COMPOSE_SERVICE" \
      bash -c "$cmds")

    log_success "Firewall enabled ($(grep -cv '^\s*#\|^\s*$' "$config") domains allowlisted)"
    ;;

  off)
    log_info "Disabling firewall..."
    (cd "$workspace_folder" && docker compose exec --user root "$COMPOSE_SERVICE" \
      bash -c 'iptables -F && iptables -X && iptables -P OUTPUT ACCEPT')
    log_success "Firewall disabled (full outbound access restored)"
    ;;

  status)
    (cd "$workspace_folder" && docker compose exec --user root "$COMPOSE_SERVICE" \
      iptables -L -n -v)
    ;;

  *)
    log_error "Usage: devc firewall <on|off|status> [config_file]"
    exit 1
    ;;
  esac
}

cmd_wrapper() {
  local name="${1:-}"

  if [[ -z "$name" ]]; then
    # List all wrappers
    if [[ ! -d "$WRAPPER_DIR" ]] || [[ -z "$(ls -A "$WRAPPER_DIR" 2>/dev/null)" ]]; then
      log_info "No wrappers generated yet. Use 'devc up --flake <ref>' to create one."
      return
    fi
    log_info "Generated wrappers ($WRAPPER_DIR/):"
    for d in "$WRAPPER_DIR"/*/; do
      [[ -d "$d" ]] || continue
      echo "  $(basename "$d")"
    done
  else
    # Show a specific wrapper
    local wrapper_path="$WRAPPER_DIR/$name/flake.nix"
    if [[ ! -f "$wrapper_path" ]]; then
      log_error "No wrapper found: $name"
      log_info "Run 'devc wrapper' to list available wrappers"
      exit 1
    fi
    log_info "Wrapper: $WRAPPER_DIR/$name/flake.nix"
    echo "---"
    cat "$wrapper_path"
  fi
}

cmd_self_install() {
  local install_dir="$HOME/.local/bin"
  local install_path="$install_dir/devc"

  mkdir -p "$install_dir"
  ln -sf "$SCRIPT_DIR/$SCRIPT_NAME" "$install_path"

  log_success "Installed 'devc' to $install_path"

  if [[ ":$PATH:" != *":$install_dir:"* ]]; then
    log_warn "$install_dir is not in your PATH"
    log_info "Add this to your shell profile:"
    echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
  fi
}

cmd_update() {
  log_info "Updating devc..."

  if ! git -C "$SCRIPT_DIR" rev-parse --is-inside-work-tree &>/dev/null; then
    log_error "Not a git repository: $SCRIPT_DIR"
    log_info "Re-clone with: rm -rf ~/.claude-devcontainer && git clone https://github.com/trailofbits/claude-code-devcontainer ~/.claude-devcontainer"
    exit 1
  fi

  local before_sha after_sha
  before_sha=$(git -C "$SCRIPT_DIR" rev-parse HEAD)

  if ! git -C "$SCRIPT_DIR" pull --ff-only; then
    log_error "Update failed. Try: cd $SCRIPT_DIR && git pull"
    exit 1
  fi

  after_sha=$(git -C "$SCRIPT_DIR" rev-parse HEAD)

  if [[ "$before_sha" == "$after_sha" ]]; then
    log_success "Already up to date"
  else
    log_success "Updated from ${before_sha:0:7} to ${after_sha:0:7}"
  fi
}

cmd_dot() {
  cmd_template "."
  cmd_up "."
}

# Main command dispatcher
main() {
  if [[ $# -eq 0 ]]; then
    print_usage
    exit 1
  fi

  local command="$1"
  shift

  case "$command" in
  .)
    cmd_dot
    ;;
  up)
    cmd_up "$@"
    ;;
  rebuild)
    cmd_rebuild "$@"
    ;;
  down)
    cmd_down "$@"
    ;;
  shell)
    cmd_shell
    ;;
  exec)
    [[ "${1:-}" == "--" ]] && shift
    cmd_exec "$@"
    ;;
  upgrade)
    cmd_upgrade
    ;;
  wrapper)
    cmd_wrapper "$@"
    ;;
  mounts)
    cmd_mounts
    ;;
  mount)
    cmd_mount "$@"
    ;;
  cp)
    cmd_cp "$@"
    ;;
  firewall)
    cmd_firewall "$@"
    ;;
  self-install)
    cmd_self_install
    ;;
  update)
    cmd_update
    ;;
  template)
    cmd_template "$@"
    ;;
  help | --help | -h)
    print_usage
    ;;
  *)
    log_error "Unknown command: $command"
    print_usage
    exit 1
    ;;
  esac
}

main "$@"
